-- 銀行預金管理テーブル
CREATE TABLE `BANKS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DAY` char(10) NOT NULL,
  `BANK` varchar(20) NOT NULL,
  `DEPOSIT` char(1) NOT NULL DEFAULT '0',
  `BALANCE` decimal(10,0) NOT NULL,
  `INFO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
