#!/bin/bash
#  $1 Source file (Full path)
#  $2 id of Pictures
if test $# -lt 1; then
  echo ERROR: Two parameters does not exists.
  exit 1
fi
if test -f $1; then
  echo $1
else
  echo ERROR: $1 does not a file.
  exit 1
fi

# Convert $1 to thumbnail.
fn=`basename $1`
echo ImageMagick convert it to ~/Pictures/Small/${fn}
convert  -geometry 64x64 $1 ~/Pictures/Small/${fn}

# Insert thumbnal to BINDATA table.
cd /home/user/workspace/python3/BINDATA/tools
python3 InsBINDATA.py ~/Pictures/Small/${fn}

# Get id of BINDATA table, Update Pictures table using the id of BINDATA
cd /home/user/workspace/python3/bin
python3 update_pictures_bindata.py $2
