-- 画像ファイル管理
CREATE TABLE `Pictures` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(100) NOT NULL,
  `CREATOR` varchar(50) NOT NULL,
  `PATH` varchar(500) NOT NULL UNIQUE,
  `MARK` varchar(10) DEFAULT NULL,
  `INFO` varchar(100) DEFAULT NULL,
  `FAV` char(1) DEFAULT '0',
  `COUNT` int(8) DEFAULT '0',
  `BINDATA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=279 DEFAULT CHARSET=utf8;

